from assignment_13 import *
from assignment_14 import *
from assignment_15 import *
from assignment_16 import *
from assignment_17 import *
from assignment_18 import *
from assignment_19 import *
from assignment_20 import *
from assignment_21 import *
from coding_practice_24 import *
from coding_practice_25 import *
from coding_practice_26 import *
from coding_practice_27 import *
from coding_practice_28 import *
from coding_practice_35 import *
from codingPractice23 import *
from codingPractice_13 import *
from codingPractice_14 import *
from codingPractice_15 import *
from codingPractice_16 import *
from codingPractice_17 import *
from codingPractice_18 import *
from codingPractice_19 import *
from codingPractice_20 import *
from codingPractice_21 import *
from codingPractice_32 import *
from codingPractice_33 import *
from codingPractice_34 import *
from codingPractice_2A import *
from f2 import *
from f4 import *
from competitive_coding_qs import *
from GrandAssignment_2 import * 
from GrandAssignment_5 import *
from Idp_preparation_series_1 import *
from Idp_Preparation_Series_2 import *